#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 26 17:16:24 2017

@author: deepak.ppe
"""

#import os
#import csv
import pandas as pd


sbimastercat = pd.read_csv('/Users/dkumar7/Google Drive/PyProj/finminion/sbi_master.csv')
homeloan = "R.A.C.P.C."
cab = "PayTm|PAYTM|UBER"
cafe = "COFFEE DAY|STARBUCKS|CHAI POINT|BARISTA"
cash = "WITHDRAWAL"
creditcard = "XX9753"
entertainment = "Netflix|Bookmyshow|PVR|V BANGALO"
familysocial = "CORNER HOUS|FUNCITY|DUNKIN"
grocery = "SPENCERS|FAMILIES|NAMDHARI|MORE MEGASTORE|urdoorstep.com|Aishwarya"
imps1 = "XXXXXXXXXXX4682"
imps2 = "XXXXXXX7579"
impsnani = "XXXXXXXXXXX0796"
impsvajjar = "XXXXXXX1286"
impsmama = "XXXXXXX0162"
impssibu = "XXXXXXX0436"
medical = "DR SUNNY|LIFE LINE|LEVINE|St Johns|EYE FOUNDATION|Eye Foundation"
school = "GYAN|AKSHARA"
sharekhan = "SSKI"
shop = "AMAZON|myntra|"
social = "TIPSY|GREENS BAR|BLISTERING BARNACLES|BREWSKY|FISHERMANS|BLACK PEARL|FOOD PILIGRIM|FENNYS|HOOT"
utilities = "SPECTRANET"

class - if (grepl(homeloan, exp$Description), "Home Loan", 
                     ifelse(grepl(impsmama, exp$Description), "Mama",
                            ifelse(grepl(social, exp$Description), "Social",
                                   ifelse(grepl(cab, exp$Description), "Cab",
                                          ifelse(grepl(cash, exp$Description), "Cash",
                                                 ifelse(grepl(cafe, exp$Description), "Cafe",
                                                        ifelse(grepl(creditcard, exp$Description), "Card",
                                                               ifelse(grepl(entertainment, exp$Description), "Entertainment",
                                                                      ifelse(grepl(familysocial, exp$Description), "Family Social",
                                                                             ifelse(grepl(medical, exp$Description), "medical",
                                                                                    ifelse(grepl(grocery, exp$Description), "grocery",
                                                                                           ifelse(grepl(imps1, exp$Description), "imps1",
                                                                                                  ifelse(grepl(imps2, exp$Description), "imps2",
                                                                                                         ifelse(grepl(impsnani, exp$Description), "impsnani",
                                                                                                                ifelse(grepl(impsvajjar, exp$Description), "impsvajjar",
                                                                                                                       ifelse(grepl(impssibu, exp$Description), "impssibu",
                                                                                                                              ifelse(grepl(school, exp$Description), "school",
                                                                                                                                     ifelse(grepl(shop, exp$Description), "shop",
                                                                                                                                            ifelse(grepl(utilities, exp$Description), "utilities", "Other")))))))))))))))))))
                                                                                                                          